const config = require('.utils/config')
const express = require('express')
const app = express()
const cors = require('cors')
const notesRouter = require('.controllers/notes')
const middleware = require('./utils/middleware')
const logger = require('./utils/logger')
const mongoose = require('mongoose')